/// @function	vngen_object_init();
/// @author		Lucas Chasteen <lucas.chasteen@xgasoft.com>
/// @copyright	XGASOFT 2020, All Rights Reserved
function vngen_object_init() {

	/*
	Initializes all the necessary functions for running VNgen in the current object. 
	Must be run in the Create event of each object containing VNgen code.

	No parameters

	Example usage: 
	   vngen_object_init();
	*/

	//Initialize event functions
	event_id = -1; //Tracks events and sets order in timeline
	event_count = 0; //Tracks the total number of events in the timeline
	event_current = 0; //The integer ID of the current event
	event_exit = true; //Sets whether to process actions in the current event
	event_previous = -1; //The integer ID of the previous event
	event_pause = 0; //Sets the delay between events
	event_skip = -1; //Sets the event ID to skip to
	event_skip_id = -1; //Stores the event ID to be skipped to on the next frame
	event_skip_label = -1; //Stores the event label to be skipped to on the next frame
	event_skip_load = -1; //Sets the event to be skipped to when vngen_file_load is run
	event_skip_perform = true; //Enables or disables performing skipped events
	event_skip_read = false; //Enables or disables skipping read events until an unread event is reached
	event_skip_src = -1; //Stores the source event being skipped from
	event_noskip = false; //Sets whether the current event's actions are skippable (does not apply to event/read skip)
	event_label[0] = ""; //Stores event labels in an array

	//Initialize action functions
	action_id = -1; //Tracks actions and sets order in timeline
	action_count = 0; //Tracks the total number of actions in an event
	action_complete = 0; //Tracks the number of actions in the event which have been completed
	action_current = 0; //The integer ID of the current action
	action_previous = -1; //The integer ID of the previous action (not used by all actions)
	action_pause = 0; //Sets the delay between actions (see vngen_event_pause)
	action_skip = false; //Sets whether to perform pauses and transitions
	action_skip_active = false; //Sets whether to skip the target event's actions after event skip

	//Initialize button functions
	button_count = 0; //Tracks the number of existing buttons
	button_hover = -1; //Tracks which button is currently highlighted, if any
	button_active = -1; //Tracks which button is currently selected, if any
	button_result = -1; //The ID of the most recent button to be selected

	//Initialize option functions
	option_id = -1; //Tracks options and sets order in timeline
	option_count = 0; //Tracks the number of existing options
	option_current = 0; //The integer ID of the current option
	option_exit = true; //Sets whether to process options in the current block
	option_pause = 0; //Sets the delay before and after options are displayed
	option_hover = -1; //Tracks which option is currently highlighted, if any
	option_active = -1; //Tracks which option is currently selected, if any
	option_result = -1; //The ID of the most recent option to be selected
	option_snd_hover = -1; //Sets the sound to be played when an option is hovered
	option_snd_select = -1; //Sets the sound to be played when an option is selected
	option_x = 0; //Sets the global horizontal offset for options
	option_y = 0; //Sets the global vertical offset for options

	//Initialize text properties
	text_continue = false; //Prevents text actions being marked complete until user input marks them complete
	text_label_auto = ""; //Stores the current speaker(s) as a string which can be displayed with labels
	text_pause = false; //Prevents the typewriter effect from progressing until user input unpauses the effect
	text_xprevious = 0; //Stores the most recent text horizontal position
	text_yprevious = 0; //Stores the most recent text vertical position

	//Initialize animation properties
	keyframe_id = -1; //Tracks animation keyframes and sets order in scripts
	keyframe_count = 0; //Tracks the total number of keyframes in an animation script
	keyframe_current = 0; //The integer ID of the current keyframe

	//Initialize mouse properties
	mouse_hover = false; //Tracks whether the mouse is currently hovering text links or options
	mouse_hover_enable = true; //Enables or disables changing cursor states for certain actions
	mouse_hover_check = false; //Tracks the current hover state for cursor changes
	mouse_xprevious = mouse_x; //Tracks the previous mouse horizontal coordinate
	mouse_yprevious = mouse_y; //Tracks the previous mouse vertical coordinate

	//Initialize character properties
	attach_count = 0;
	attach_length = 118; //DO NOT CHANGE THIS
	surf_highlight = -1;

	//Initialize time properties
	time_frame = delta_time/1000000;
	time_speed = game_get_speed(gamespeed_fps);
	time_target = 1/time_speed;
	time_offset = time_frame/time_target;

	//Initialize room properties
	room_xoffset = 0;
	room_yoffset = 0;

	//Initialize debug console properties
	if (global.dp_width < 2500) and (global.dp_height < 1400) {
	   fnt_console = fnt_console_small;
	} else {
	   fnt_console = fnt_console_large;
	}

	//Create primary data structures         // Memory map:
	//------------------------------         // [ 0      | 1        | 2          | 3          | 4        | 5      | 6       | 7       | 8    | 9    | 10   | 11        | 12        | 13    | 14    | 15    | 16    | 17    | 18    | 19   | 20          | 21         | 22        | 23            | 24            | 25           | 26           | 27     | 28       | 29             | 30             | 31       | 32           | 33           | 34                | 35                | 36         | 37                 | 38                 | 39          | 40           | 41        | 42        | 43           | 44           | 45          | 46         | 47             | 48             | 49            | 50         | 51        | 52          | 53           | 54      | 55      | 56           | 57           | 58        | 59          | 60         | 61              | 62             | 63               | 64                | 65           | 66           | 67                | 68                | 69             | 70               | 71     | 72       | 73     | 74       | 75     | 76      | 77      | 78        | 79            | 80            | 81        | 82           | 83        | 84      | 85     | 86          | 87            | 88       | 89        | 90        | 91        | 92        | 93         | 94        | 95          | 96          | 97               | 98                 | 99            | 100            | 101            | 102            | 103            | 104             | 105    | 106          | 107          | 108      | 109         | 110      | 111            | 112      | 113      | 114           | 115  | 116       | 117     | 118        | 119         | 120    | 121    | 122        | 123        | 124          | 125         | 126        | 127           | 128          | 129      | 130         | 131          | 132         | 133          | 134  | 135       | 136         | 137             | 138              | 139            | 140         | 141            | 142           | 143            | 144         | 145         | 146         | 147         | 148          | 149         | 150          | 151              ]
	ds_perspective = ds_grid_create(118, 1); // [ id     | sh_surf  | null       | null       | width    | height | xoffset | yoffset | x    | y    | null | zoom      | strength  | rot   | null  | null  | null  | null  | null  | null | fade_surf   | fade_alpha | fade_draw | null          | null          | temp_xoffset | temp_yoffset | temp_x | temp_y   | temp_zoom      | temp_strength  | temp_rot | anim_xoffset | anim_yoffset | anim_temp_xoffset | anim_temp_yoffset | null       | null               | null               | final_width | final_height | final_x   | final_y   | final_xscale | final_yscale | final_rot   | null       | null           | null           | null          | null       | null      | null        | null         | null    | null    | null         | null         | null      | null        | null       | null            | null           | null             | null              | null         | null         | null              | null              | null           | null             | shader | sh_frame | sh_amt | sh_float | sh_mat | sh_samp | sh_time | animation | anim_keyframe | anim_duration | anim_loop | anim_reverse | anim_ease | anim_x  | anim_y | anim_zoom   | anim_strength | anim_rot | null      | null      | null      | null      | null       | anim_time | anim_temp_x | anim_temp_y | anim_temp_zoom   | anim_temp_strength | anim_temp_rot | null           | null           | null           | null           | null            | null   | null         | null         | null     | null        | null     | null           | null     | null     | null          | null | null      | null    ]
	ds_scene = ds_grid_create(127, 0);       // [ id     | sprite   | left       | top        | width    | height | xorig   | yorig   | x    | y    | z    | xscale    | yscale    | rot   | col1  | col2  | col3  | col4  | alpha | time | fade_sprite | fade_alpha | fade_time | offset_xscale | offset_yscale | temp_xorig   | temp_yorig   | temp_x | temp_y   | temp_xscale    | temp_yscale    | temp_rot | temp_col1    | temp_col2    | temp_col3         | temp_col4         | temp_alpha | temp_offset_xscale | temp_offset_yscale | final_width | final_height | final_x   | final_y   | final_xscale | final_yscale | final_rot   | transition | trans_keyframe | trans_duration | trans_reverse | trans_left | trans_top | trans_width | trans_height | trans_x | trans_y | trans_xscale | trans_yscale | trans_rot | trans_alpha | trans_time | trans_temp_left | trans_temp_top | trans_temp_width | trans_temp_height | trans_temp_x | trans_temp_y | trans_temp_xscale | trans_temp_yscale | trans_temp_rot | trans_temp_alpha | shader | sh_frame | sh_amt | sh_float | sh_mat | sh_samp | sh_time | animation | anim_keyframe | anim_duration | anim_loop | anim_reverse | anim_ease | anim_x  | anim_y | anim_xscale | anim_yscale   | anim_rot | anim_col1 | anim_col2 | anim_col3 | anim_col4 | anim_alpha | anim_time | anim_temp_x | anim_temp_y | anim_temp_xscale | anim_temp_yscale   | anim_temp_rot | anim_temp_col1 | anim_temp_col2 | anim_temp_col3 | anim_temp_col4 | anim_temp_alpha | deform | def_keyframe | def_duration | def_loop | def_reverse | def_ease | def_point_data | def_time | def_surf | def_fade_surf | null | img_index | img_num | foreground | repeat      | null   | null   | null       | null       | null         | null        | scene_surf ]
	ds_character = ds_grid_create(132, 0);   // [ id     | spr_body | left       | top        | width    | height | xorig   | yorig   | x    | y    | z    | xscale    | yscale    | rot   | col1  | col2  | col3  | col4  | alpha | time | fade_surf   | fade_alpha | fade_time | offset_xscale | offset_yscale | temp_xorig   | temp_yorig   | temp_x | temp_y   | temp_xscale    | temp_yscale    | temp_rot | temp_col1    | temp_col2    | temp_col3         | temp_col4         | temp_alpha | temp_offset_xscale | temp_offset_yscale | final_width | final_height | final_x   | final_y   | final_xscale | final_yscale | final_rot   | transition | trans_keyframe | trans_duration | trans_reverse | trans_left | trans_top | trans_width | trans_height | trans_x | trans_y | trans_xscale | trans_yscale | trans_rot | trans_alpha | trans_time | trans_temp_left | trans_temp_top | trans_temp_width | trans_temp_height | trans_temp_x | trans_temp_y | trans_temp_xscale | trans_temp_yscale | trans_temp_rot | trans_temp_alpha | shader | sh_frame | sh_amt | sh_float | sh_mat | sh_samp | sh_time | animation | anim_keyframe | anim_duration | anim_loop | anim_reverse | anim_ease | anim_x  | anim_y | anim_xscale | anim_yscale   | anim_rot | anim_col1 | anim_col2 | anim_col3 | anim_col4 | anim_alpha | anim_time | anim_temp_x | anim_temp_y | anim_temp_xscale | anim_temp_yscale   | anim_temp_rot | anim_temp_col1 | anim_temp_col2 | anim_temp_col3 | anim_temp_col4 | anim_temp_alpha | deform | def_keyframe | def_duration | def_loop | def_reverse | def_ease | def_point_data | def_time | def_surf | def_fade_surf | null | img_index | img_num | spr_idle   | spr_talk    | face_x | face_y | face_pause | face_time  | face_index   | face_number | char_surf  | attach_data   | highlight    | hl_alpha | text_active | audio_active ]
	ds_emote = ds_grid_create(118, 0);       // [ id     | sprite   | null       | null       | width    | height | xorig   | yorig   | x    | y    | z    | xscale    | yscale    | rot   | col1  | col2  | col3  | col4  | alpha | time | null        | null       | null      | null          | null          | null         | null         | null   | null     | null           | null           | null     | null         | null         | null              | null              | null       | null               | null               | final_width | final_height | final_x   | final_y   | final_xscale | final_yscale | final_rot   | null       | null           | null           | null          | null       | null      | null        | null         | null    | null    | null         | null         | null      | null        | null       | null            | null           | null             | null              | null         | null         | null              | null              | null           | null             | null   | null     | null   | null     | null   | null    | null    | null      | null          | null          | null      | null         | null      | null    | null   | null        | null          | null     | null      | null      | null      | null      | null       | null      | null        | null        | null             | null               | null          | null           | null           | null           | null           | null            | null   | null         | null         | null     | null        | null     | null           | null     | null     | null          | null | img_index | img_num ]
	ds_textbox = ds_grid_create(118, 0);     // [ id     | sprite   | left       | top        | width    | height | xorig   | yorig   | x    | y    | z    | xscale    | yscale    | rot   | col1  | col2  | col3  | col4  | alpha | time | fade_sprite | fade_alpha | fade_time | offset_xscale | offset_yscale | temp_xorig   | temp_yorig   | temp_x | temp_y   | temp_xscale    | temp_yscale    | temp_rot | temp_col1    | temp_col2    | temp_col3         | temp_col4         | temp_alpha | temp_offset_xscale | temp_offset_yscale | final_width | final_height | final_x   | final_y   | final_xscale | final_yscale | final_rot   | transition | trans_keyframe | trans_duration | trans_reverse | trans_left | trans_top | trans_width | trans_height | trans_x | trans_y | trans_xscale | trans_yscale | trans_rot | trans_alpha | trans_time | trans_temp_left | trans_temp_top | trans_temp_width | trans_temp_height | trans_temp_x | trans_temp_y | trans_temp_xscale | trans_temp_yscale | trans_temp_rot | trans_temp_alpha | shader | sh_frame | sh_amt | sh_float | sh_mat | sh_samp | sh_time | animation | anim_keyframe | anim_duration | anim_loop | anim_reverse | anim_ease | anim_x  | anim_y | anim_xscale | anim_yscale   | anim_rot | anim_col1 | anim_col2 | anim_col3 | anim_col4 | anim_alpha | anim_time | anim_temp_x | anim_temp_y | anim_temp_xscale | anim_temp_yscale   | anim_temp_rot | anim_temp_col1 | anim_temp_col2 | anim_temp_col3 | anim_temp_col4 | anim_temp_alpha | deform | def_keyframe | def_duration | def_loop | def_reverse | def_ease | def_point_data | def_time | def_surf | def_fade_surf | null | img_index | img_num ]
	ds_text = ds_grid_create(152, 0);        // [ id     | name     | left       | top        | width    | height | xorig   | yorig   | x    | y    | z    | xscale    | yscale    | rot   | col1  | col2  | col3  | col4  | alpha | time | fade_surf   | fade_alpha | fade_time | offset_xscale | offset_yscale | temp_xorig   | temp_yorig   | temp_x | temp_y   | temp_xscale    | temp_yscale    | temp_rot | temp_col1    | temp_col2    | temp_col3         | temp_col4         | temp_alpha | temp_offset_xscale | temp_offset_yscale | final_width | final_height | final_x   | final_y   | final_xscale | final_yscale | final_rot   | transition | trans_keyframe | trans_duration | trans_reverse | trans_left | trans_top | trans_width | trans_height | trans_x | trans_y | trans_xscale | trans_yscale | trans_rot | trans_alpha | trans_time | trans_temp_left | trans_temp_top | trans_temp_width | trans_temp_height | trans_temp_x | trans_temp_y | trans_temp_xscale | trans_temp_yscale | trans_temp_rot | trans_temp_alpha | shader | sh_frame | sh_amt | sh_float | sh_mat | sh_samp | sh_time | animation | anim_keyframe | anim_duration | anim_loop | anim_reverse | anim_ease | anim_x  | anim_y | anim_xscale | anim_yscale   | anim_rot | anim_col1 | anim_col2 | anim_col3 | anim_col4 | anim_alpha | anim_time | anim_temp_x | anim_temp_y | anim_temp_xscale | anim_temp_yscale   | anim_temp_rot | anim_temp_col1 | anim_temp_col2 | anim_temp_col3 | anim_temp_col4 | anim_temp_alpha | deform | def_keyframe | def_duration | def_loop | def_reverse | def_ease | def_point_data | def_time | def_surf | def_fade_surf | null | null      | null    | null       | char_height | char_x | char_y | char_pause | char_speed | char_index   | char_number | text_surf  | text_complete | redraw_index | font     | shadow      | outline      | temp_shadow | temp_outline | text | text_orig | text_halign | text_line_break | text_line_height | text_line_data | markup_font | markup_yoffset | markup_shadow | markup_outline | markup_col1 | markup_col2 | markup_col3 | markup_col4 | markup_speed | markup_time | markup_pause | markup_link_data ]
	ds_label = ds_grid_create(141, 0);       // [ id     | null     | left       | top        | width    | height | xorig   | yorig   | x    | y    | z    | xscale    | yscale    | rot   | col1  | col2  | col3  | col4  | alpha | time | fade_surf   | fade_alpha | fade_time | offset_xscale | offset_yscale | temp_xorig   | temp_yorig   | temp_x | temp_y   | temp_xscale    | temp_yscale    | temp_rot | temp_col1    | temp_col2    | temp_col3         | temp_col4         | temp_alpha | temp_offset_xscale | temp_offset_yscale | final_width | final_height | final_x   | final_y   | final_xscale | final_yscale | final_rot   | transition | trans_keyframe | trans_duration | trans_reverse | trans_left | trans_top | trans_width | trans_height | trans_x | trans_y | trans_xscale | trans_yscale | trans_rot | trans_alpha | trans_time | trans_temp_left | trans_temp_top | trans_temp_width | trans_temp_height | trans_temp_x | trans_temp_y | trans_temp_xscale | trans_temp_yscale | trans_temp_rot | trans_temp_alpha | shader | sh_frame | sh_amt | sh_float | sh_mat | sh_samp | sh_time | animation | anim_keyframe | anim_duration | anim_loop | anim_reverse | anim_ease | anim_x  | anim_y | anim_xscale | anim_yscale   | anim_rot | anim_col1 | anim_col2 | anim_col3 | anim_col4 | anim_alpha | anim_time | anim_temp_x | anim_temp_y | anim_temp_xscale | anim_temp_yscale   | anim_temp_rot | anim_temp_col1 | anim_temp_col2 | anim_temp_col3 | anim_temp_col4 | anim_temp_alpha | deform | def_keyframe | def_duration | def_loop | def_reverse | def_ease | def_point_data | def_time | def_surf | def_fade_surf | null | null      | null    | null       | char_height | char_x | char_y | null       | null       | char_index   | char_number | label_surf | label_auto    | redraw_mode  | font     | shadow      | outline      | temp_shadow | temp_outline | text | text_orig | text_halign | text_line_break | text_line_height | text_line_data | label_event ]
	ds_prompt = ds_grid_create(125, 0);      // [ id     | spr_auto | left       | top        | width    | height | xorig   | yorig   | x    | y    | z    | xscale    | yscale    | rot   | col1  | col2  | col3  | col4  | alpha | time | fade_sprite | fade_alpha | fade_time | offset_xscale | offset_yscale | temp_xorig   | temp_yorig   | temp_x | temp_y   | temp_xscale    | temp_yscale    | temp_rot | temp_col1    | temp_col2    | temp_col3         | temp_col4         | temp_alpha | temp_offset_xscale | temp_offset_yscale | final_width | final_height | final_x   | final_y   | final_xscale | final_yscale | final_rot   | transition | trans_keyframe | trans_duration | trans_reverse | trans_left | trans_top | trans_width | trans_height | trans_x | trans_y | trans_xscale | trans_yscale | trans_rot | trans_alpha | trans_time | trans_temp_left | trans_temp_top | trans_temp_width | trans_temp_height | trans_temp_x | trans_temp_y | trans_temp_xscale | trans_temp_yscale | trans_temp_rot | trans_temp_alpha | shader | sh_frame | sh_amt | sh_float | sh_mat | sh_samp | sh_time | animation | anim_keyframe | anim_duration | anim_loop | anim_reverse | anim_ease | anim_x  | anim_y | anim_xscale | anim_yscale   | anim_rot | anim_col1 | anim_col2 | anim_col3 | anim_col4 | anim_alpha | anim_time | anim_temp_x | anim_temp_y | anim_temp_xscale | anim_temp_yscale   | anim_temp_rot | anim_temp_col1 | anim_temp_col2 | anim_temp_col3 | anim_temp_col4 | anim_temp_alpha | deform | def_keyframe | def_duration | def_loop | def_reverse | def_ease | def_point_data | def_time | def_surf | def_fade_surf | null | img_index | img_num | spr_idle   | spr_active  | null   | null   | trigger    | null       | prompt_index ]
	ds_button = ds_grid_create(146, 0);      // [ id     | sprite   | left       | top        | width    | height | xorig   | yorig   | x    | y    | z    | xscale    | yscale    | rot   | col1  | col2  | col3  | null  | alpha | time | null        | null       | null      | offset_xscale | offset_yscale | null         | null         | temp_x | temp_y   | temp_xscale    | temp_yscale    | temp_rot | null         | null         | null              | null              | temp_alpha | null               | null               | final_width | final_height | final_x   | final_y   | final_xscale | final_yscale | final_rot   | transition | trans_keyframe | trans_duration | trans_reverse | trans_left | trans_top | trans_width | trans_height | trans_x | trans_y | trans_xscale | trans_yscale | trans_rot | trans_alpha | trans_time | trans_temp_left | trans_temp_top | trans_temp_width | trans_temp_height | trans_temp_x | trans_temp_y | trans_temp_xscale | trans_temp_yscale | trans_temp_rot | trans_temp_alpha | null   | null     | null   | null     | null   | null    | null    | null      | null          | anim_duration | null      | null         | anim_ease | anim_x  | anim_y | anim_xscale | anim_yscale   | null     | anim_col1 | null      | null      | null      | null       | anim_time | anim_temp_x | anim_temp_y | anim_temp_xscale | anim_temp_yscale   | null          | anim_temp_col1 | null           | null           | null           | null            | null   | null         | null         | null     | null        | null     | null           | null     | null     | null          | null | img_index | img_num | spr_hover  | spr_select  | text_x | text_y | trigger    | null       | null         | null        | text_surf  | snd_hover     | snd_select   | font     | null        | null         | null        | null         | text | null      | null        | null            | text_line_height | null           | init_width  | init_height    | init_x        | init_y         | init_xscale | init_yscale ]
	ds_option = ds_grid_create(146, 0);      // [ id     | sprite   | left       | top        | width    | height | xorig   | yorig   | x    | y    | z    | xscale    | yscale    | rot   | col1  | col2  | col3  | null  | alpha | time | null        | null       | null      | offset_xscale | offset_yscale | null         | null         | temp_x | temp_y   | temp_xscale    | temp_yscale    | temp_rot | null         | null         | null              | null              | temp_alpha | null               | null               | final_width | final_height | final_x   | final_y   | final_xscale | final_yscale | final_rot   | transition | trans_keyframe | trans_duration | trans_reverse | trans_left | trans_top | trans_width | trans_height | trans_x | trans_y | trans_xscale | trans_yscale | trans_rot | trans_alpha | trans_time | trans_temp_left | trans_temp_top | trans_temp_width | trans_temp_height | trans_temp_x | trans_temp_y | trans_temp_xscale | trans_temp_yscale | trans_temp_rot | trans_temp_alpha | null   | null     | null   | null     | null   | null    | null    | null      | null          | anim_duration | null      | null         | anim_ease | anim_x  | anim_y | anim_xscale | anim_yscale   | null     | anim_col1 | null      | null      | null      | null       | anim_time | anim_temp_x | anim_temp_y | anim_temp_xscale | anim_temp_yscale   | null          | anim_temp_col1 | null           | null           | null           | null            | null   | null         | null         | null     | null        | null     | null           | null     | null     | null          | null | img_index | img_num | spr_hover  | spr_select  | text_x | text_y | trigger    | null       | null         | null        | text_surf  | null          | null         | font     | null        | null         | null        | null         | text | null      | null        | null            | text_line_height | null           | init_width  | init_height    | init_x        | init_y         | init_xscale | init_yscale ]
	ds_audio = ds_grid_create(37, 0);        // [ id     | sound    | type       | event      | duration | null   | start   | end     | pos  | vol  | null | null      | pitch     | null  | null  | null  | null  | null  | null  | time | fade_sound  | fade_vol   | fade_time | null          | null          | null         | null         | null   | temp_vol | null           | temp_pitch     | null     | null         | null         | null              | null              | temp_time  ] ( Types:           | 0 = sfx            | 1 = sfx l   | 2 = voice    | 3 = music | 4 = sfx p | 5 = sfx l p  | 6 = voice p  | 7 = music p )
	ds_vox = ds_grid_create(37, 0);          // [ id     | sound    | type       | null       | null     | null   | null    | null    | null | vol  | null | pitch_min | pitch_max | null  | null  | null  | null  | null  | null  | time | fade_sound  | fade_vol   | fade_time | null          | null          | null         | null         | null   | temp_vol | temp_pitch_min | temp_pitch_max | null     | null         | null         | null              | null              | temp_time  ] ( Types:           | 0 = vox            | 1 = vox p   )
	ds_effect = ds_grid_create(113, 0);      // [ id     | state    | null       | null       | null     | null   | null    | null    | null | null | null | null      | null      | null  | null  | null  | null  | null  | null  | null | null        | null       | null      | null          | null          | null         | null         | null   | null     | null           | null           | null     | null         | null         | null              | null              | null       | null               | null               | null        | null         | null      | null      | null         | null         | null        | null       | null           | null           | null          | null       | null      | null        | null         | null    | null    | null         | null         | null      | null        | null       | null            | null           | null             | null              | null         | null         | null              | null              | null           | null             | null   | null     | null   | null     | null   | null    | null    | null      | null          | null          | null      | null         | null      | null    | null   | null        | null          | null     | null      | null      | null      | null      | null       | null      | null        | null        | null             | null               | null          | null           | null           | null           | null           | null            | effect | ef_keyframe  | ef_duration  | ef_loop  | ef_reverse  | ef_ease  | ef_var_data    | ef_time  ]

	//Secondary data structures
	//ds_attach = ds_grid_create(118, 0);    // [ id     | sprite   | left       | top        | width    | height | xorig   | yorig   | x    | y    | z    | xscale    | yscale    | rot   | col1  | col2  | col3  | col4  | alpha | time | fade_sprite | fade_alpha | fade_time | offset_xscale | offset_yscale | temp_xorig   | temp_yorig   | temp_x | temp_y   | temp_xscale    | temp_yscale    | temp_rot | temp_col1    | temp_col2    | temp_col3         | temp_col4         | temp_alpha | temp_offset_xscale | temp_offset_yscale | final_width | final_height | final_x   | final_y   | final_xscale | final_yscale | final_rot   | transition | trans_keyframe | trans_duration | trans_reverse | trans_left | trans_top | trans_width | trans_height | trans_x | trans_y | trans_xscale | trans_yscale | trans_rot | trans_alpha | trans_time | trans_temp_left | trans_temp_top | trans_temp_width | trans_temp_height | trans_temp_x | trans_temp_y | trans_temp_xscale | trans_temp_yscale | trans_temp_rot | trans_temp_alpha | shader | sh_frame | sh_amt | sh_float | sh_mat | sh_samp | sh_time | animation | anim_keyframe | anim_duration | anim_loop | anim_reverse | anim_ease | anim_x  | anim_y | anim_xscale | anim_yscale   | anim_rot | anim_col1 | anim_col2 | anim_col3 | anim_col4 | anim_alpha | anim_time | anim_temp_x | anim_temp_y | anim_temp_xscale | anim_temp_yscale   | anim_temp_rot | anim_temp_col1 | anim_temp_col2 | anim_temp_col3 | anim_temp_col4 | anim_temp_alpha | deform | def_keyframe | def_duration | def_loop | def_reverse | def_ease | def_point_data | def_time | def_surf | def_fade_surf | null | img_index | img_num ]
	//ds_link = ds_grid_create(10, 0);       // [ null   | state    | ev_type    | event      | width    | height | null    | null    | x    | y    ]
	//ds_point = ds_grid_create(4, 0);       // [ xpoint | ypoint   | tmp_xpoint | tmp_ypoint ]
	//ds_float = ds_grid_create(3, 0);       // [ id     | uniform  | value      ]
	//ds_samp = ds_grid_create(3, 0);        // [ id     | uniform  | value      ]
	//ds_mat = ds_grid_create(2, 0);         // [ id     | uniform  ]
	//ds_var = ds_grid_create(2, 0);         // [ var    | temp_var ]

	//Set default perspective values
	ds_perspective[# prop._id, 0] = 0;                    //ID
	ds_perspective[# prop._width, 0] = global.dp_width;   //Width
	ds_perspective[# prop._height, 0] = global.dp_height; //Height
	ds_perspective[# prop._per_zoom, 0] = 1;              //Zoom
	ds_perspective[# prop._per_str, 0] = 1;               //Strength
	ds_perspective[# prop._fade_src, 0] = -1;             //Temp surf
	ds_perspective[# prop._anim, 0] = -1;                 //Animation
	ds_perspective[# prop._anim_xscale, 0] = 1;           //Animation X scale
	ds_perspective[# prop._anim_yscale, 0] = 1;           //Animation Y scale
	ds_perspective[# prop._anim_alpha, 0] = 1;            //Animation alpha
	ds_perspective[# prop._oxscale, 0] = 1;               //Offset X scale (N/A)
	ds_perspective[# prop._oyscale, 0] = 1;               //Offset Y scale (N/A)
	ds_perspective[# prop._shader, 0] = -1;               //Shader
	ds_perspective[# prop._src, 0] = -1;                  //Shader surface
	ds_perspective[# prop._sh_float_data, 0] = -1;        //Shader float data
	ds_perspective[# prop._sh_mat_data, 0] = -1;          //Shader matrix data
	ds_perspective[# prop._sh_samp_data, 0] = -1;         //Shader sampler data



}
